/**
 * Theme fixtures — the BeardGit Dark / Light pair, as the Rust side
 * actually serializes them.
 *
 * ## Why this is generated, not hand-written
 *
 * This file used to hardcode the two themes, with a docstring saying the
 * values "mirror `crates/storage/src/theme.rs` derivation applied to
 * `themes/beardgit_dark.toml`". A hand-mirror of a derivation drifts the
 * moment the derivation changes, and nothing detects it — which meant
 * every visual baseline in `tests/visual/` was rendered against a copy of
 * the theme rather than the theme. Those baselines could never catch a
 * theming regression, which is exactly what they look like they're for.
 *
 * The data now comes from `src/lib/stores/__fixtures__/themes.json`,
 * generated by `storage::theme::tests::regenerate_theme_fixtures` and
 * pinned byte-for-byte by `test_theme_fixtures_match_live_serialization`.
 * Regenerate with:
 *
 *     cargo test -p storage regenerate_theme_fixtures -- --ignored
 *     npm run test:visual:update
 *
 * The `with { type: "json" }` attribute is required: this module is
 * imported by Playwright specs, which load through Node's ESM loader, and
 * `package.json` sets `"type": "module"`. Without it, collection fails for
 * the *entire* Playwright project.
 */

import type { ThemeData, ThemeMeta } from "../../lib/types";
import themes from "../../lib/stores/__fixtures__/themes.json" with { type: "json" };

const BY_ID: Record<string, ThemeData> = themes;

const DARK = BY_ID["beardgit-dark"];
const LIGHT = BY_ID["beardgit-light"];

export function makeDarkTheme(overrides: Partial<ThemeData> = {}): ThemeData {
  return { ...DARK, ...overrides };
}

export function makeLightTheme(overrides: Partial<ThemeData> = {}): ThemeData {
  return { ...LIGHT, ...overrides };
}

export function makeThemeData(
  mode: "dark" | "light" = "dark",
  overrides: Partial<ThemeData> = {},
): ThemeData {
  return mode === "dark" ? makeDarkTheme(overrides) : makeLightTheme(overrides);
}

export function makeThemeMetaList(): ThemeMeta[] {
  return [DARK.meta, LIGHT.meta];
}
